#!/usr/bin/ruby
#
# Author:: Johannes Krude
# Copyright:: (c) Johannes Krude 2009
# License:: AGPL3
#
#--
# This file is part of filehosting.
#
# filehosting is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# filehosting is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with filehosting.  If not, see <http://www.gnu.org/licenses/>.
#++
#
puts "Content-Type: text/html; charset=utf-8"
puts

args= ENV["PATH_INFO"].split("/")[1..-1]

require "filehosting/html"
require "filehosting/string"
require "filehosting/config"
require "filehosting/configfilereader"
require "filehosting/error"

require "uuidtools"

etcreader= FileHosting::ConfigFileReader.new("/etc/filehostingrc.cgi")

config= FileHosting::Config.new(etcreader)

if args.size != 1
	puts FileHosting::HTML.error_page("wrong arguments")
	exit
end
begin
	uuid= UUID.parse(args[0])
rescue ArgumentError => e
	puts FileHosting::HTML.error_page(e)
	exit
end

begin
	fileinfo= config.datasource.fileinfo(uuid)
	puts FileHosting::HTML.page(fileinfo.filename.to_html, fileinfo.to_html)
rescue FileHosting::Error => e
	puts FileHosting::HTML.error_page(e)
	exit
end
