#!/usr/bin/ruby
#
# Author:: Johannes Krude
# Copyright:: (c) Johannes Krude 2009
# License:: AGPL3
#
#--
# This file is part of filehosting.
#
# filehosting is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# filehosting is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with filehosting.  If not, see <http://www.gnu.org/licenses/>.
#++
#

require "filehosting/html"
require "filehosting/string"
require "filehosting/config"
require "filehosting/configfilereader"
require "filehosting/error"

require "uuidtools"

puts "Content-Type: text/html; charset=utf-8"
puts

tags= nil
if ENV["QUERY_STRING"]
	vars= FileHosting::HTML.parse_get(ENV["QUERY_STRING"])
	if vars and vars["tags"]
		tags= vars["tags"].split("+")
	end
end

etcreader= FileHosting::ConfigFileReader.new("/etc/filehostingrc.cgi")

config= FileHosting::Config.new(etcreader)

begin
	unless tags
		puts FileHosting::HTML.page("search", FileHosting::HTML.use_template("search_new.eruby", binding), "search.css")
	else
		search_result= config.datasource.search_tags(tags)
		puts FileHosting::HTML.page("search: #{tags.to_html}", FileHosting::HTML.use_template("search.eruby", binding), "search.css")
	end
rescue FileHosting::Error => e
	puts FileHosting::HTML.error_page(e)
	exit
end
